"""
Perform recursive near-offset reconstruction using a trained conditional
diffusion model.

The script loads one seismic shot gather, constructs the initial conditioning
patch from the recorded traces adjacent to the missing region, and recursively
propagates the predicted patch toward the missing near offsets.

Multiple samples are generated in parallel by using batch_size independent
noise realizations. Their mean is used as the final reconstruction, while
their standard deviation provides an uncertainty estimate.
"""

import argparse
import os

import numpy as np
import torch as th
import torch.nn.functional as F
from code.datasets import normalizer_vel, denormalizer_vel, normalizer_depth
import scipy.io as sio

from code import logger
from code.script_util import (
    NUM_CLASSES,
    model_and_diffusion_defaults,
    create_model_and_diffusion,
    add_dict_to_argparser,
    args_to_dict,
)


def main():
    """
    Load a trained model and recursively reconstruct missing near-offset traces.

    The inference workflow contains the following steps:

    1. Parse the model and sampling configurations.
    2. Construct the conditional U-Net and diffusion process.
    3. Load the trained EMA model parameters.
    4. Extract the initial conditioning patch from the recorded traces.
    5. Generate multiple stochastic reconstructions at each recursive step.
    6. Use each reconstructed patch as the conditioning input for the next
       near-offset extrapolation step.
    7. Compute the ensemble mean, uncertainty, and reconstruction error.
    8. Save the results as a MATLAB file.
    """

    # Parse sampling and diffusion configurations from the command line.
    args = create_argparser().parse_args()

    # Use a CUDA-enabled GPU for diffusion-model inference.
    device = th.device('cuda')

    # Initialize the logging system.
    logger.configure()

    # Training iteration of the model checkpoint used for reconstruction.
    train_step = 20000

    # Create an output directory according to the selected sampling method.
    if not args.use_ddim:
        # Store results generated by the full DDPM reverse process.
        dir_output = f'./output/ddpm/step{train_step}/'
    else:
        # Store DDIM results according to the timestep-respacing setting,
        # such as ddim2, ddim10, or another configured sampling schedule.
        dir_output = f'./output/{args.timestep_respacing}/step{train_step}/'

    # Create the output directory when it does not already exist.
    os.makedirs(dir_output, exist_ok=True)

    logger.log("creating model and diffusion...")

    # Construct the conditional U-Net and the corresponding diffusion process
    # using the same architecture and diffusion settings as those used during
    # model training.
    model, diffusion = create_model_and_diffusion(
        **args_to_dict(
            args,
            model_and_diffusion_defaults().keys()
        )
    )

    # Load the trained model parameters.
    #
    # With the default model_path, the complete checkpoint path is:
    #
    #     ./checkpoints/ema_0.999_020000.pt
    #
    # The model architecture and all parameter names must exactly match those
    # used when this checkpoint was created.
    model.load_state_dict(
        th.load(
            f'{args.model_path}{(train_step):06d}.pt',
            map_location=device
        )
    )

    # Transfer the model to the selected GPU.
    model.to(device=device)

    # Disable training-specific operations such as dropout.
    model.eval()

    # Dictionary reserved for optional model-conditioning variables.
    model_kwargs = {}

    # Class conditioning is disabled by default for the seismic reconstruction
    # framework. This branch is retained for compatibility with the original
    # class-conditional diffusion implementation.
    if args.class_cond:
        classes = th.randint(
            low=0,
            high=NUM_CLASSES,
            size=(args.batch_size,),
            device=dist_util.dev()
        )
        model_kwargs["y"] = classes

    # Select either the full stochastic DDPM sampler or the respaced DDIM
    # sampler.
    sample_fn = (
        diffusion.p_sample_loop
        if not args.use_ddim
        else diffusion.ddim_sample_loop
    )

    # Mean-squared-error criterion used only for controlled validation, where
    # the artificially removed reference traces remain available.
    criterion = th.nn.MSELoss()

    # List of shot-gather indices to reconstruct.
    data_list = [1]

    # Process each selected seismic shot gather independently.
    for id in data_list:
        print(
            f'Sampling start for data {id} '
            f'with batch size {args.batch_size}'
        )

        # Load one seismic shot gather from a MATLAB file.
        dict = sio.loadmat(f'../dataset/seam/train/data{id}.mat')

        # Extract the two-dimensional seismic array with shape [nt, nr_ori].
        shot = dict['shot']

        # nt is the number of temporal samples, and nr_ori is the original
        # number of receiver traces.
        nt, nr_ori = shot.shape

        # Lateral shift between the target patch and conditioning patch.
        # The current self-supervised framework uses a one-trace shift.
        width_gap = 1

        # Number of traces treated as missing in this controlled validation
        # example.
        miss_trace = 10

        # Index marking the beginning of the last miss_trace traces.
        #
        # In this validation configuration, these traces are retained as the
        # reference near-offset data but are excluded from the initial
        # conditioning patch.
        far_start = nr_ori - miss_trace

        # Extract the initial conditioning patch immediately adjacent to the
        # artificially removed region.
        #
        # The patch has shape [nt, width_size] and provides the recorded offset
        # context used to generate the next one-trace-shifted patch.
        shot_far = shot[
            :,
            far_start-args.width_size:far_start
        ]

        # Extract the reference patch containing the final width_size traces.
        #
        # Its last miss_trace traces serve as the ground truth for quantitative
        # evaluation of the reconstructed missing region.
        real_nearshot = shot[:, -args.width_size:]

        # Convert shot_far to a four-dimensional tensor with shape:
        #
        #     [1, 1, nt, width_size]
        #
        # The dimensions represent batch, channel, time, and receiver trace.
        shot_far = th.tensor(
            shot_far,
            dtype=th.float32
        ).unsqueeze(0).unsqueeze(1).to(device=device)

        # Convert the reference near-offset patch to the same NCHW tensor
        # format used by the diffusion model.
        real_nearshot = th.tensor(
            real_nearshot,
            dtype=th.float32
        ).unsqueeze(0).unsqueeze(1).to(device=device)

        # Replicate the same conditioning patch across the batch dimension.
        #
        # Each batch item is initialized with an independent random noise
        # realization by the diffusion sampler. Therefore, batch_size controls
        # the number of ensemble reconstructions used for uncertainty
        # quantification rather than the number of different shot gathers.
        shot_far = shot_far.repeat(
            args.batch_size,
            1,
            1,
            1
        )

        # Recursively propagate the reconstruction across the missing region.
        #
        # Each iteration predicts a patch shifted by one trace relative to the
        # current conditioning patch. The predicted patch is then used as the
        # conditioning input for the next recursive extrapolation step.
        for ir in range(miss_trace):
            print(f'sampling missing trace index {ir}')

            # Generate batch_size realizations of the next reconstructed patch.
            #
            # The requested output tensor has shape:
            #
            #     [batch_size, out_channels, nt, width_size]
            #
            # sample contains the final output from the selected DDPM or DDIM
            # reverse-sampling process.
            sample, _, _ = sample_fn(
                model,
                shot_far,
                (
                    args.batch_size,
                    args.out_channels,
                    nt,
                    args.width_size
                ),
                clip_denoised=args.clip_denoised,
                model_kwargs=model_kwargs,
            )

            # Use the newly reconstructed patch as the conditioning context for
            # the next one-trace recursive extrapolation step.
            #
            # clone() creates a separate tensor while preserving the predicted
            # values and ensemble dimension.
            shot_far = sample.clone()

        # Disable gradient tracking during ensemble statistics and evaluation.
        with th.no_grad():
            # Compute the ensemble-mean reconstruction across all independent
            # diffusion realizations.
            #
            # The resulting tensor has shape [1, 1, nt, width_size].
            pred = sample.mean(
                dim=0,
                keepdim=True
            )

            # Compute the pointwise ensemble standard deviation as the
            # uncertainty estimate.
            std = sample.std(
                dim=0,
                keepdim=True
            )

            # Evaluate reconstruction accuracy over the final miss_trace
            # traces only.
            #
            # This metric is available because the current experiment
            # artificially removes recorded traces for controlled validation.
            accs = criterion(
                pred[:, :, :, -miss_trace:],
                real_nearshot[:, :, :, -miss_trace:]
            )

        # Save the ensemble-mean prediction, uncertainty map, and MSE value in
        # MATLAB format.
        sio.savemat(
            f'{dir_output}data{id}_batch{args.batch_size}_out.mat',
            {
                # Reconstructed patch after removing singleton batch and
                # channel dimensions.
                'predict': pred.squeeze().cpu().numpy(),

                # Pointwise standard deviation across ensemble realizations.
                'uq': std.squeeze().cpu().numpy(),

                # Scalar MSE over the artificially removed reference traces.
                'accs': accs.item()
            }
        )

    logger.log("sampling complete")


def create_argparser():
    """
    Create the command-line argument parser for recursive sampling.

    The sampling-specific settings defined here are combined with the model
    and diffusion defaults used during training.

    Returns
    -------
    argparse.ArgumentParser
        Configured command-line argument parser.
    """

    defaults = dict(
        # Clip each predicted clean seismic patch to the range [-1, 1].
        clip_denoised=True,

        # Use DDIM sampling by default. Setting this to False uses the full
        # DDPM reverse process.
        use_ddim=True,

        # Number of independent diffusion realizations generated in parallel.
        #
        # This value controls the ensemble size used to compute the mean
        # reconstruction and uncertainty map.
        batch_size=20,

        # Prefix of the EMA checkpoint filename.
        model_path="./checkpoints/ema_0.999_",

        # Lateral width W of the conditioning and reconstructed patches.
        width_size=32,
    )

    # Add the U-Net and diffusion-process defaults. The value of
    # timestep_respacing determines the number of DDIM sampling steps.
    defaults.update(model_and_diffusion_defaults())

    # Construct the command-line parser.
    parser = argparse.ArgumentParser()

    # Register all default values as command-line arguments.
    add_dict_to_argparser(parser, defaults)

    return parser


if __name__ == "__main__":
    # Execute recursive near-offset reconstruction only when the script is run
    # directly.
    main()
